if(NOT LOCAL_CMAKE_LISTS_DIR)
    message(FATAL_ERROR "LOCAL_CMAKE_LISTS_DIR must be set before including AddCMakeListDirectory.cmake")
endif()

get_property(LOCAL_CMAKE_LISTS_ADDED_DIRS
    GLOBAL
    PROPERTY CMAKE_HELPER_ADDED_CMAKE_LIST_DIRS)

if(NOT "${LOCAL_CMAKE_LISTS_DIR}" IN_LIST LOCAL_CMAKE_LISTS_ADDED_DIRS)
    if(LOCAL_CMAKE_LISTS_BINARY_DIR)
        add_subdirectory("${LOCAL_CMAKE_LISTS_DIR}" "${LOCAL_CMAKE_LISTS_BINARY_DIR}")
    else()
        add_subdirectory("${LOCAL_CMAKE_LISTS_DIR}")
    endif()

    list(APPEND LOCAL_CMAKE_LISTS_ADDED_DIRS "${LOCAL_CMAKE_LISTS_DIR}")
    set_property(GLOBAL
        PROPERTY CMAKE_HELPER_ADDED_CMAKE_LIST_DIRS
            ${LOCAL_CMAKE_LISTS_ADDED_DIRS})
endif()

unset(LOCAL_CMAKE_LISTS_ADDED_DIRS)
