if(LOCAL_PATH)
    set(LOCAL_CMAKE_LISTS_ROOT_DIR "${LOCAL_PATH}")
else()
    get_filename_component(LOCAL_CMAKE_LISTS_ROOT_DIR "${CMAKE_PARENT_LIST_FILE}" DIRECTORY)
endif()

file(GLOB_RECURSE LOCAL_CMAKE_LISTS_FILES
    LIST_DIRECTORIES false
    "${LOCAL_CMAKE_LISTS_ROOT_DIR}/CMakeLists.txt")
list(SORT LOCAL_CMAKE_LISTS_FILES)

foreach(LOCAL_CMAKE_LISTS_FILE IN LISTS LOCAL_CMAKE_LISTS_FILES)
    get_filename_component(LOCAL_CMAKE_LISTS_DIR "${LOCAL_CMAKE_LISTS_FILE}" DIRECTORY)

    if(NOT LOCAL_CMAKE_LISTS_DIR STREQUAL LOCAL_CMAKE_LISTS_ROOT_DIR)
        file(RELATIVE_PATH LOCAL_CMAKE_LISTS_RELATIVE_DIR
            "${LOCAL_CMAKE_LISTS_ROOT_DIR}"
            "${LOCAL_CMAKE_LISTS_DIR}")
        set(LOCAL_CMAKE_LISTS_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/${LOCAL_CMAKE_LISTS_RELATIVE_DIR}")
        include("${LOCAL_BUILD_SYSTEM_PATH}/internal/AddCMakeListDirectory.cmake")
    endif()
endforeach()

unset(LOCAL_CMAKE_LISTS_BINARY_DIR)
unset(LOCAL_CMAKE_LISTS_DIR)
unset(LOCAL_CMAKE_LISTS_FILE)
unset(LOCAL_CMAKE_LISTS_FILES)
unset(LOCAL_CMAKE_LISTS_RELATIVE_DIR)
unset(LOCAL_CMAKE_LISTS_ROOT_DIR)
