get_filename_component(LOCAL_CMAKE_LISTS_PARENT_DIR "${CMAKE_PARENT_LIST_FILE}" DIRECTORY)

file(GLOB LOCAL_CMAKE_LISTS_CHILDREN
    LIST_DIRECTORIES true
    "${LOCAL_CMAKE_LISTS_PARENT_DIR}/*")
list(SORT LOCAL_CMAKE_LISTS_CHILDREN)

foreach(LOCAL_CMAKE_LISTS_CHILD IN LISTS LOCAL_CMAKE_LISTS_CHILDREN)
    if(IS_DIRECTORY "${LOCAL_CMAKE_LISTS_CHILD}" AND EXISTS "${LOCAL_CMAKE_LISTS_CHILD}/CMakeLists.txt")
        file(RELATIVE_PATH LOCAL_CMAKE_LISTS_RELATIVE_DIR
            "${LOCAL_CMAKE_LISTS_PARENT_DIR}"
            "${LOCAL_CMAKE_LISTS_CHILD}")
        set(LOCAL_CMAKE_LISTS_DIR "${LOCAL_CMAKE_LISTS_CHILD}")
        set(LOCAL_CMAKE_LISTS_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/${LOCAL_CMAKE_LISTS_RELATIVE_DIR}")
        include("${LOCAL_BUILD_SYSTEM_PATH}/internal/AddCMakeListDirectory.cmake")
    endif()
endforeach()

unset(LOCAL_CMAKE_LISTS_BINARY_DIR)
unset(LOCAL_CMAKE_LISTS_CHILD)
unset(LOCAL_CMAKE_LISTS_CHILDREN)
unset(LOCAL_CMAKE_LISTS_DIR)
unset(LOCAL_CMAKE_LISTS_PARENT_DIR)
unset(LOCAL_CMAKE_LISTS_RELATIVE_DIR)
