if(NOT LOCAL_MODULE)
    message(FATAL_ERROR "LOCAL_MODULE must be set before including BUILD_EXTERNAL_PROJECT")
endif()

if(NOT LOCAL_EXTERNAL_SOURCE_DIR)
    message(FATAL_ERROR "BUILD_EXTERNAL_PROJECT requires LOCAL_EXTERNAL_SOURCE_DIR")
endif()

include(ExternalProject)

set(LOCAL_EXTERNAL_BINARY "${LOCAL_EXTERNAL_BINARY_DIR}")
if(NOT LOCAL_EXTERNAL_BINARY)
    set(LOCAL_EXTERNAL_BINARY "${CMAKE_BINARY_DIR}/_deps/${LOCAL_MODULE}-build")
endif()

set(LOCAL_EXTERNAL_INSTALL "${LOCAL_EXTERNAL_INSTALL_COMMAND}")
if(NOT DEFINED LOCAL_EXTERNAL_INSTALL_COMMAND)
    set(LOCAL_EXTERNAL_INSTALL ${CMAKE_COMMAND} -E true)
endif()

set(LOCAL_EXTERNAL_BUILD "${LOCAL_EXTERNAL_BUILD_COMMAND}")
if(NOT LOCAL_EXTERNAL_BUILD AND LOCAL_EXTERNAL_TARGETS)
    set(LOCAL_EXTERNAL_BUILD
        ${CMAKE_COMMAND} --build <BINARY_DIR> --target ${LOCAL_EXTERNAL_TARGETS})
endif()

set(LOCAL_EXTERNAL_IMPORTED_COUNT 0)
if(LOCAL_EXTERNAL_IMPORTED_TARGETS)
    list(LENGTH LOCAL_EXTERNAL_IMPORTED_TARGETS LOCAL_EXTERNAL_IMPORTED_COUNT)
endif()

set(LOCAL_EXTERNAL_LOCATION_COUNT 0)
if(LOCAL_EXTERNAL_IMPORTED_LOCATIONS)
    list(LENGTH LOCAL_EXTERNAL_IMPORTED_LOCATIONS LOCAL_EXTERNAL_LOCATION_COUNT)
endif()

if(NOT LOCAL_EXTERNAL_IMPORTED_COUNT EQUAL LOCAL_EXTERNAL_LOCATION_COUNT)
    message(FATAL_ERROR "LOCAL_EXTERNAL_IMPORTED_TARGETS and LOCAL_EXTERNAL_IMPORTED_LOCATIONS must have the same length")
endif()

ExternalProject_Add(${LOCAL_MODULE}
    SOURCE_DIR "${LOCAL_EXTERNAL_SOURCE_DIR}"
    BINARY_DIR "${LOCAL_EXTERNAL_BINARY}"
    CMAKE_ARGS
        ${LOCAL_EXTERNAL_CMAKE_ARGS}
    BUILD_COMMAND
        ${LOCAL_EXTERNAL_BUILD}
    INSTALL_COMMAND
        ${LOCAL_EXTERNAL_INSTALL}
    BUILD_BYPRODUCTS
        ${LOCAL_EXTERNAL_BUILD_BYPRODUCTS}
    DEPENDS
        ${LOCAL_EXTERNAL_DEPENDS}
    USES_TERMINAL_CONFIGURE TRUE
    USES_TERMINAL_BUILD TRUE)

if(LOCAL_EXTERNAL_IMPORTED_COUNT GREATER 0)
    math(EXPR LOCAL_EXTERNAL_IMPORTED_LAST "${LOCAL_EXTERNAL_IMPORTED_COUNT} - 1")
    foreach(LOCAL_EXTERNAL_IMPORTED_INDEX RANGE ${LOCAL_EXTERNAL_IMPORTED_LAST})
        list(GET LOCAL_EXTERNAL_IMPORTED_TARGETS ${LOCAL_EXTERNAL_IMPORTED_INDEX} LOCAL_EXTERNAL_IMPORTED_TARGET)
        list(GET LOCAL_EXTERNAL_IMPORTED_LOCATIONS ${LOCAL_EXTERNAL_IMPORTED_INDEX} LOCAL_EXTERNAL_IMPORTED_LOCATION)

        add_library(${LOCAL_EXTERNAL_IMPORTED_TARGET} STATIC IMPORTED GLOBAL)
        set_target_properties(${LOCAL_EXTERNAL_IMPORTED_TARGET} PROPERTIES
            IMPORTED_LOCATION "${LOCAL_EXTERNAL_IMPORTED_LOCATION}")

        if(LOCAL_EXPORT_C_INCLUDES)
            set_target_properties(${LOCAL_EXTERNAL_IMPORTED_TARGET} PROPERTIES
                INTERFACE_INCLUDE_DIRECTORIES "${LOCAL_EXPORT_C_INCLUDES}")
        endif()

        set(LOCAL_EXTERNAL_IMPORTED_DEPENDENCIES
                ${LOCAL_STATIC_LIBRARIES}
                ${LOCAL_SHARED_LIBRARIES}
                ${LOCAL_INTERFACE_LIBRARIES}
                ${LOCAL_OBJECT_LIBRARIES}
                ${LOCAL_HEADER_LIBRARIES})

        if(LOCAL_EXTERNAL_IMPORTED_DEPENDENCIES)
            target_link_libraries(${LOCAL_EXTERNAL_IMPORTED_TARGET}
                INTERFACE
                    ${LOCAL_EXTERNAL_IMPORTED_DEPENDENCIES})
        endif()

        add_dependencies(${LOCAL_EXTERNAL_IMPORTED_TARGET} ${LOCAL_MODULE})
    endforeach()
endif()

unset(LOCAL_EXTERNAL_BINARY)
unset(LOCAL_EXTERNAL_BUILD)
unset(LOCAL_EXTERNAL_INSTALL)
unset(LOCAL_EXTERNAL_IMPORTED_COUNT)
unset(LOCAL_EXTERNAL_LOCATION_COUNT)
unset(LOCAL_EXTERNAL_IMPORTED_LAST)
unset(LOCAL_EXTERNAL_IMPORTED_INDEX)
unset(LOCAL_EXTERNAL_IMPORTED_TARGET)
unset(LOCAL_EXTERNAL_IMPORTED_LOCATION)
unset(LOCAL_EXTERNAL_IMPORTED_DEPENDENCIES)
