if(NOT LOCAL_MODULE)
    message(FATAL_ERROR "LOCAL_MODULE must be set before including BUILD_PREBUILT")
endif()

set(LOCAL_PREBUILT_TYPE "${LOCAL_PREBUILT_MODULE_TYPE}")
if(NOT LOCAL_PREBUILT_TYPE)
    set(LOCAL_PREBUILT_TYPE STATIC)
endif()

set(LOCAL_PREBUILT_FILE "${LOCAL_PREBUILT_LOCATION}")
if(NOT LOCAL_PREBUILT_FILE)
    list(GET LOCAL_SRC_FILES 0 LOCAL_PREBUILT_FILE)
endif()

if(NOT LOCAL_PREBUILT_FILE)
    message(FATAL_ERROR "BUILD_PREBUILT requires LOCAL_PREBUILT_LOCATION or LOCAL_SRC_FILES")
endif()

add_library(${LOCAL_MODULE} ${LOCAL_PREBUILT_TYPE} IMPORTED GLOBAL)
set_target_properties(${LOCAL_MODULE} PROPERTIES
    IMPORTED_LOCATION ${LOCAL_PREBUILT_FILE})

if(LOCAL_EXPORT_C_INCLUDES)
    set_target_properties(${LOCAL_MODULE} PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${LOCAL_EXPORT_C_INCLUDES}")
endif()

set(LOCAL_DEPENDENCIES
        ${LOCAL_STATIC_LIBRARIES}
        ${LOCAL_SHARED_LIBRARIES}
        ${LOCAL_INTERFACE_LIBRARIES}
        ${LOCAL_OBJECT_LIBRARIES}
        ${LOCAL_HEADER_LIBRARIES})

if(LOCAL_DEPENDENCIES)
    target_link_libraries(${LOCAL_MODULE}
        INTERFACE
            ${LOCAL_DEPENDENCIES})
endif()

unset(LOCAL_DEPENDENCIES)
unset(LOCAL_PREBUILT_FILE)
unset(LOCAL_PREBUILT_TYPE)
