foreach(LOCAL_SRC_DIR IN LISTS LOCAL_SRC_DIRS)
    aux_source_directory(${LOCAL_SRC_DIR} LOCAL_COLLECTED_SRC_FILES)
    list(APPEND LOCAL_SRC_FILES ${LOCAL_COLLECTED_SRC_FILES})
    unset(LOCAL_COLLECTED_SRC_FILES)
endforeach()

unset(LOCAL_SRC_DIR)
